### ISSUE TITLE
Why I can't reproduce the result?

### ISSUE THREAD

**Issue by rockywind** [HDETR/H-PETR-3D#1]
Hi, author
    I trained the [model](https://github.com/HDETR/H-PETR-3D/blob/main/projects/configs/petrv2/hybrid_petrv2_vovnet_gridmask_p4_800x320_lambda1_group4_t1800.py) follow the guide.
My training script is below:
``` tools/dist_train.sh projects/configs/petrv2/hybrid_petrv2_vovnet_gridmask_p4_800x320_lambda1_group4_t1800.py 8 --work-dir work_dirs/hybrid_petrv2_vovnet_gridmask_p4_800x320_lambda1_group4_t1800/ ```
My last epoch's result is below:
![image](https://user-images.githubusercontent.com/14838781/204857360-c176c386-3927-46e6-9225-c31a82070467.png)

**Comment by PkuRainBow** [comment]
@LittlePey Please help to check the possible reasons.

**Comment by LittlePey** [comment]
@rockywind Hi, if you want to get 42.59 mAP and  52.38 NDS, you need to train the model with our [36 epoch config](https://github.com/HDETR/H-PETR-3D/blob/main/projects/configs/petrv2/hybrid_petrv2_vovnet_gridmask_p4_800x320_lambda1_group4_t1800_ep36.py). If you want to get 41.93 mAP and 51.23 NDS, your results seem within the variance.

**Comment by rockywind** [comment]
Hi
I trained the model with the [36 epoch config](https://github.com/HDETR/H-PETR-3D/blob/main/projects/configs/petrv2/hybrid_petrv2_vovnet_gridmask_p4_800x320_lambda1_group4_t1800_ep36.py).
The result is below:
![image](https://user-images.githubusercontent.com/14838781/205197173-ee96ef71-1b3d-4959-946b-561c44574eef.png)

**Comment by PkuRainBow** [comment]
@rockywind Thanks for your interest in our work! 

We encourage you to try other hyper-parameters with more positive samples as we have not spent too much effort on tuning the parameters on PETR3D.

It would be great if you could share more results in the future.

**Comment by rockywind** [comment]
Thanks
